### ISSUE TITLE
add a better gif in readme.md

### ISSUE THREAD

**Issue by Rupeshiya** [Rupeshiya/Tic-Tac-Toe-CLI#2]
Add a gif following the same commands given in readme.md

**Comment by Rupeshiya** [comment]
sure @luizbaldi  go ahead.

**Comment by luizbaldi** [comment]
PR opened on #3

**Comment by Rupeshiya** [comment]
thanks for PR @luizbaldi

**Comment by Rupeshiya** [comment]
@luizbaldi  you can also go ahead with https://github.com/Rupeshiya/FunPacketCli/issues if you want .
